#!/usr/bin/env python3
"""
End-to-end smoke test for the Python bindings of `hidden-volume-ffi`.

Loads the cdylib via the auto-generated `hidden_volume_ffi` module
(which uses `ctypes` to talk to the Rust library) and exercises the
full sync FFI surface.

Run with:
    cd bindings/python
    python3 test_smoke.py

Exit code 0 = all assertions held. Any failure prints the raised
exception with traceback and exits non-zero.

This test is the canary for FFI binding correctness: if it passes,
the auto-generated bindings round-trip every type we expose
(constructors, opaque handles, byte arrays, optional values, vector
returns, error mapping). It does NOT test Kotlin/Swift/Ruby
specifically — but those bindings are generated by the same uniffi
machinery from the same Rust source, so a panic-free Python run is
strong evidence the others work too.
"""

from __future__ import annotations
import os
import sys
import tempfile
import traceback

# Make the bindings module importable from this script's directory.
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
# NOTE: setting os.environ["LD_LIBRARY_PATH"] here would be a no-op —
# glibc snapshots LD_LIBRARY_PATH at process start, so mutating it
# in-process does not affect later dlopen(). The uniffi-generated
# bindings load the cdylib by absolute path anyway, so no env wiring
# is needed.

import hidden_volume_ffi as hv  # noqa: E402


def with_temp_path(f):
    """Run `f(path)` in a fresh tempfile path; clean up afterwards."""
    fd, path = tempfile.mkstemp(prefix="hv_py_smoke_", suffix=".bin")
    os.close(fd)
    os.unlink(path)  # we want the path; let create() make the file
    try:
        return f(path)
    finally:
        try:
            os.unlink(path)
        except FileNotFoundError:
            pass


def test_create_open_roundtrip():
    def body(path):
        # Create a fresh space.
        space = hv.SpaceHandle.create(
            path=path,
            password=b"pw",
            argon=hv.ArgonPreset.MIN,
            initial_garbage_chunks=0,
            superblock_replicas=1,
        )
        assert space.commit_seq() == 1, f"expected initial commit_seq=1, got {space.commit_seq()}"

        # Write a KV entry + a log entry in one batch.
        new_seq = space.commit([
            hv.WriteOp.PUT(namespace=1, key=b"username", value=b"alice"),
            hv.WriteOp.APPEND_LOG(namespace=3, log_id=1, payload=b"hi"),
        ])
        assert new_seq == 2, f"expected post-commit seq=2, got {new_seq}"
        assert space.commit_seq() == 2

        # Read back.
        got = space.get(namespace=1, key=b"username")
        assert got == b"alice", f"expected b'alice', got {got!r}"

        log = space.read_log(namespace=3, log_id=1)
        assert log == b"hi", f"expected b'hi', got {log!r}"

        # Drop, reopen, verify durability.
        del space
        reopened = hv.SpaceHandle.open(path=path, password=b"pw")
        assert reopened.commit_seq() == 2
        assert reopened.get(1, b"username") == b"alice"
        del reopened

        # Wrong password → AuthFailed.
        try:
            hv.SpaceHandle.open(path=path, password=b"wrong")
            raise AssertionError("expected AuthFailed, got success")
        except hv.HvError.AuthFailed:
            pass

    with_temp_path(body)


def test_iter_log_range():
    def body(path):
        space = hv.SpaceHandle.create(
            path=path,
            password=b"pw",
            argon=hv.ArgonPreset.MIN,
            initial_garbage_chunks=0,
            superblock_replicas=1,
        )

        ops = [
            hv.WriteOp.APPEND_LOG(namespace=3, log_id=i, payload=f"msg{i}".encode())
            for i in range(1, 21)
        ]
        space.commit(ops)

        page = space.iter_log_range(namespace=3, start=5, end=10, limit=100)
        ids = [e.log_id for e in page]
        assert ids == [5, 6, 7, 8, 9], f"expected [5..9], got {ids}"

        for entry in page:
            want = f"msg{entry.log_id}".encode()
            assert entry.payload == want, f"id={entry.log_id} payload mismatch: {entry.payload!r}"

    with_temp_path(body)


def test_verify_integrity_and_stats():
    def body(path):
        space = hv.SpaceHandle.create(
            path=path,
            password=b"pw",
            argon=hv.ArgonPreset.MIN,
            initial_garbage_chunks=0,
            superblock_replicas=1,
        )
        space.commit([
            hv.WriteOp.PUT(namespace=1, key=b"k1", value=b"v1"),
            hv.WriteOp.PUT(namespace=2, key=b"k2", value=b"v2"),
        ])

        report = space.verify_integrity()
        assert report.namespaces_verified == 2, report.namespaces_verified
        assert report.chunks_verified >= 2, report.chunks_verified

        stats = space.stats()
        assert stats.total_entries == 2, stats.total_entries
        assert stats.commit_seq == 2, stats.commit_seq

        ns_list = space.list_namespaces()
        assert sorted(ns_list) == [1, 2], ns_list

        assert space.count(namespace=1) == 1
        assert space.count(namespace=2) == 1

    with_temp_path(body)


def test_header_info_no_password():
    def body(path):
        # Create space, then drop and read header without password.
        space = hv.SpaceHandle.create(
            path=path,
            password=b"pw",
            argon=hv.ArgonPreset.MIN,
            initial_garbage_chunks=10,
            superblock_replicas=1,
        )
        del space

        info = hv.header_info(path=path)
        assert len(info.salt_hex) == 64, len(info.salt_hex)
        # v3 (2026-05-28): `container_id` is no longer in the cleartext
        # header — it is per-space derived from the versioned master
        # key. The FFI `HeaderInfo` correspondingly dropped its
        # `container_id_hex` field. See docs/en/reference/format.md §1.
        assert not hasattr(info, "container_id_hex"), (
            "v3 must NOT expose container_id in HeaderInfo"
        )
        assert info.argon_m_cost_kib > 0
        assert info.file_size_bytes > 0

    with_temp_path(body)


def test_async_surface():
    """
    Quick smoke test that the async surface generates working Python
    bindings. Uses the same handle types behind asyncio.
    """
    import asyncio

    async def body(path):
        space = await hv.AsyncSpaceHandle.create(
            path=path,
            password=b"pw",
            argon=hv.ArgonPreset.MIN,
            initial_garbage_chunks=0,
            superblock_replicas=1,
        )
        assert (await space.commit_seq()) == 1

        await space.commit([
            hv.WriteOp.PUT(namespace=1, key=b"k", value=b"v"),
        ])
        assert (await space.commit_seq()) == 2
        assert (await space.get(namespace=1, key=b"k")) == b"v"

    def run(path):
        asyncio.run(body(path))

    with_temp_path(run)


TESTS = [
    ("create_open_roundtrip", test_create_open_roundtrip),
    ("iter_log_range", test_iter_log_range),
    ("verify_integrity_and_stats", test_verify_integrity_and_stats),
    ("header_info_no_password", test_header_info_no_password),
    ("async_surface", test_async_surface),
]


def main() -> int:
    failures = 0
    for name, fn in TESTS:
        try:
            fn()
            print(f"  ok   {name}")
        except Exception:
            failures += 1
            print(f"  FAIL {name}")
            traceback.print_exc()
    if failures:
        print(f"\n{failures}/{len(TESTS)} tests failed")
        return 1
    print(f"\nall {len(TESTS)} tests passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
