// Shared dylib resolver for the plugin's Dart tests and for `bench/`.
//
// The previous per-test resolvers only searched for `hidden_volume_ffi.dll`
// (Windows extension), which made `flutter test` fail in `setUpAll`
// on macOS (`.dylib`) and Linux (`.so`). This helper picks the right
// extension for the running platform — and tries every probable
// search root — so the tests work uniformly across host OS.
//
// Naming convention: no `_test.dart` suffix so Dart's test runner
// does not auto-discover this as a test file.

import 'dart:ffi' show DynamicLibrary;
import 'dart:io';

/// Cargo build profiles to search, most-preferred first.
///
/// **`release` leads, and the order is load-bearing.** The UniFFI per-method
/// checksum table in `lib/src/bindings.dart` is generated by
/// `scripts/regen-dart-checksums.py` from whichever cdylib that script
/// resolves, and its documented build step is
/// `cargo build -p hidden-volume-ffi --release`. Release is also what
/// `scripts/release.sh` stages and what CI ships.
///
/// This file used to search `debug` first. That split the guarantee in half:
/// with both profiles built and only one refreshed,
/// `regen-dart-checksums.py --check` reported the table sound against
/// `target/release` while `flutter test` loaded `target/debug` and failed on
/// the very checksums the script had just certified. An integrity check that
/// passes on a library nobody executes is the "verified artifact is not the
/// executed artifact" split that audit HV-05 exists to close, reopened one
/// directory over.
///
/// `scripts/dylib_path.py` carries the same list for the Python side, and
/// `regen-dart-checksums.py` refuses to run when the two disagree — so this
/// constant cannot drift on its own.
const dylibProfileOrder = <String>['release', 'debug'];

/// Host-native `(prefix, stem, extension)` for the `cdylib`. macOS uses
/// `.dylib`, Linux `.so`, Windows `.dll`; `cdylib` outputs land in
/// `target/<profile>/` under the platform-default prefix and extension.
List<List<String>> _hostTriplets() {
  final triplets = <List<String>>[
    if (Platform.isMacOS) ['lib', 'hidden_volume_ffi', '.dylib'],
    if (Platform.isLinux) ['lib', 'hidden_volume_ffi', '.so'],
    if (Platform.isWindows) ['', 'hidden_volume_ffi', '.dll'],
  ];
  if (triplets.isEmpty) {
    throw StateError('unsupported host OS: ${Platform.operatingSystem}');
  }
  return triplets;
}

/// Every path [`resolveDylibPath`] will try, in the order it tries them.
///
/// Exposed so a test can assert the search honours [dylibProfileOrder]
/// rather than merely declaring it — see `test/checksum_test.dart`.
List<String> dylibCandidates() {
  final root = Directory.current.path;
  final searchRoots = <String>[
    // `flutter test` invoked from the plugin dir
    // (`experimental/flutter_plugin/hidden_volume/`) — ascend three
    // levels to find the workspace `target/`.
    '$root/../../../target',
    // `flutter test` invoked from the repo root.
    '$root/target',
  ];
  final candidates = <String>[];
  // Profile-major: a `release` build anywhere outranks a `debug` build
  // anywhere, so the preference expressed by `dylibProfileOrder` holds no
  // matter which working directory the runner was started from.
  for (final profile in dylibProfileOrder) {
    for (final base in searchRoots) {
      for (final triple in _hostTriplets()) {
        candidates.add('$base/$profile/${triple[0]}${triple[1]}${triple[2]}');
      }
    }
  }
  return candidates;
}

/// Find the built `hidden-volume-ffi` cdylib for the current host platform.
///
/// Prefers the profile the checksum table was generated from — see
/// [dylibProfileOrder]. Searches both "test runs from plugin dir" and "test
/// runs from repo root" layouts. Throws [StateError] with the full candidate
/// list if no file is found.
String resolveDylibPath() {
  final candidates = dylibCandidates();
  for (final p in candidates) {
    if (File(p).existsSync()) return p;
  }
  throw StateError('cdylib not found, searched: ${candidates.join(", ")}');
}

/// Convenience wrapper: resolve, open, return the [DynamicLibrary].
DynamicLibrary openTestDylib() => DynamicLibrary.open(resolveDylibPath());
